######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 9 14:25:16 2009
######################################################################

TEMPLATE = app
TARGET = 
LIBS = -lgloox
DEPENDPATH += .
INCLUDEPATH += /home/hryukin/_myprogs/Client/. .

# Input
HEADERS += Client.h main.h
SOURCES += Client.cpp
