# #####################################################################
# Automatically generated by qmake (2.01a) ?? 7. ??? 16:28:09 2009
# #####################################################################
TEMPLATE = app
TARGET = 
LIBS = -lgloox
CONFIG += console
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Client.cpp \
    main.cpp
HEADERS += Client.h
